language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

dist: xenial

addons:
  chrome: stable
  sauce_connect: true

env:
  - WR_TEST=no
  - WR_TEST=yes

services: xvfb

cache:
  directories:
    - node_modules

sudo: required

install:
  - ./.travis/install.sh

before_install:
  - 'if [ "$WR_TEST" = "yes" ]; then sudo sysctl kernel.unprivileged_userns_clone=1; fi'

script:
  - ./.travis/test.sh

after_success:
  - codecov

matrix:
  exclude:
    - env: WR_TEST=yes
      python: "2.7"
    - env: WR_TEST=yes
      python: "3.5"

