# pywb config file
# ========================================
#

collections:
    all: $all
    pywb:
        index_paths: ./sample_archive/cdx/
        archive_paths: ./sample_archive/warcs/

# Settings for each collection
use_js_obj_proxy: true

# Memento support, enable
enable_memento: true

# Replay content in an iframe
framed_replay: true


# uncomment and change to set default locale
# default_locale: en

# uncomment to set available locales
locales:
  - en
  - fr

