version: '3'

services:
  pywb:
    build: .
    ports:
        - 8080:8080
    volumes:
        - ./config.yaml:/webarchive/config.yaml
        - ./ssb-archive/webarchive/collections/wayback:/webarchive/collections/wayback